### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by dkdewitt** [LightBender/std.database.sql#2]
Are you still working on this?  I know you had some talk a few months ago in the forums regarding a generic Data Access Layer similar to other languages to build RDBMS libraries on top of?  Was wondering what is going on or if something else is being developed?  I think this a huge miss within D on developing better support for Databases for use since each current lib is different and/or missing features and one cant easily replace one database with another in an app.

**Comment by LightBender** [comment]
My most recent talk was on Library Design in general, nothing specific to DAL's. That said I am not working on this variant of my DAL anymore. I have have a new variant laying around on my disks that is much more idiomatic D.

The goal is not an ORM, but more like ADO.NET, low-level DB operations (connection, read/write data formats, etc.) are abstracted away but the queries themselves are not. Also swapping DB's underneath is not really a goal here. Yes, this would simplify it, but you'd still be rewriting SQL queries, for example, when moving from MSSQL to PGSQL. A goal would be to enable ORM's at a higher level though.

**Comment by LightBender** [comment]
New repo is located over here: https://github.com/LightBender/std.experimental.database.sql
